# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
client_id = "87149139000876b92a021908be6da1f0"
name = "Vault wallet"
application_url = "https://unreproducible-chemiluminescent-jacquiline.ngrok-free.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"
  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"
  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"
  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_customers,read_draft_orders,read_orders,write_draft_orders,write_metaobject_definitions,write_metaobjects,write_products,write_discounts,read_discounts"

[auth]
redirect_urls = [ "https://unreproducible-chemiluminescent-jacquiline.ngrok-free.dev/api/auth" ]

[app_proxy]
url = "https://unreproducible-chemiluminescent-jacquiline.ngrok-free.dev"
subpath = "vaultwallet"
prefix = "apps"